window.SIGNWELL_SITE_TEXT = {
  "siteTitle": "SIGN WELL · 欣緯生醫",
  "metaDescription": "SIGN WELL · 欣緯生醫 — 醫學白話文、臨床推理與值得留下的知識。",
  "brandEnglish": "SIGN WELL",
  "brandChinese": "欣緯生醫",
  "homeEyebrow": "SIGN WELL BIOMED · 欣緯生醫",
  "homeTitle1": "從臨床出發，",
  "homeTitle2": "把值得留下的醫學寫清楚。",
  "homeSubtitle": "以臨床推理、醫學教育與自費醫療觀察為核心的知識平台。從一個問題開始，整理成下一次真正用得上的答案。",
  "homeCardTitle": "醫學不只是答案，而是理解答案從哪裡來。",
  "homeCardBody": "把床邊問題、閱讀與思考整理成可回顧的知識，讓資訊回到臨床情境。",
  "dailyEyebrow": "每日更新",
  "dailyTitle": "最新文章",
  "dailyDescription": "最新整理與近期發布",
  "topicsEyebrow": "知識地圖",
  "topicsTitle": "主題分類",
  "topicsSubtitle": "依領域整理文章、臨床問題與延伸閱讀。",
  "aboutEyebrow": "關於 SIGN WELL",
  "aboutTitle": "欣緯生醫",
  "aboutBody": "一個以臨床推理、醫學教育與自費醫療觀察為核心的個人出版空間。",
  "aboutManifestoTitle": "把複雜的醫學，整理成真正能被理解與使用的知識。",
  "aboutManifestoBody": "我們重視推理、脈絡與長期可回顧性，而不只是快速堆疊資訊。",
  "aboutPeopleEyebrow": "PEOPLE",
  "aboutPeopleTitle": "我們是誰",
  "aboutPeopleSubtitle": "以不同背景與專長，共同整理值得留下的醫學與健康知識。",
  "footerTagline": "醫學白話文、臨床推理，以及值得留下的知識。",
  "footerDisclaimer": "本站不提供醫療服務、不招攬醫療業務；內容僅供醫學教育與資訊整理，不構成個別醫療建議。",
  "searchPlaceholder": "搜尋文章、主題、關鍵字…",
  "shareEyebrow": "分享我們",
  "shareTitle": "把 SIGN WELL 分享給需要的人。",
  "shareSubtitle": "文章分享與 QR Code 已統一放在每篇文章的 Article ID Card。"
};
